### ISSUE TITLE
Is this being supported? If I don't hear back soon I will report for removal from HACS

### ISSUE THREAD

**Issue by user897943** [xMrVizzy/philips-airpurifier#24]
Hi, first of all thanks for all the work that has already been put into this.

This integration is available on HACS, I just purchased 2 air purifiers 2889/10 and they are not working. I posted on another issue but I will paste it below. It doesn't appear that this integration is being actively supported. If that's the case please remove it from HACS. If I don't hear back I will assume it's abandoned and report for removal from HACS, quoting this post.

There is an issue from January 5 or January 2 that has not even seen a response. This should not be on HACS if it's not supported.

Thank you.

I just took delivery of the 2889/10 model, enrolled successfully in the app and can control it via the app, added the config to HA and it shows on the entity list with a red circle and unavailable. I installed the latest version from HACS.

```
fan:
  # 1st floor
  - platform: philips_airpurifier
    host: 10.0.0.114
    name: Air Purifier - 1st floor

  # 2nd floor
  - platform: philips_airpurifier
    host: 10.0.0.115
    name: Air Purifier - 2nd floor
```

I keep getting this error on the log:

```
Error adding entities for domain fan with platform philips_airpurifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 349, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 510, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity fan.air_purifier_1st_floor cannot be added a second time to an entity platform
```
What could be the issue? Please help, I have every device at home linked to HA so I'd really like to control the purifiers from the same interface, thank you.

Edit: steps I tried:
To use every version since master - none worked, same error as above
I logged into the docker and py-air-ctrl was not installed so I ran pip3 install py-air-ctrl and it installed successfully - still does not work
restarted HA several times - no diffence
restart the whole raspi4 - no difference
I also made sure to update the two units, there was a notice on the app telling me to unplug, wait 30 secs and replug, this updated the firmware

**Comment by ekeih** [comment]
Starting your issue with a threat is a really bad idea.

Otherwise, I just installed this custom component and it works fine for me, so the claim that it is generally broken and should be removed is also simply untrue.

**Comment by user897943** [comment]
> Starting your issue with a threat is a really bad idea.
> 
> Otherwise, I just installed this custom component and it works fine for me, so the claim that it is generally broken and should be removed is also simply untrue.

You need to chill, it's not a threat, the first thing I said is a thanks and the title is to make it clear that if this is unsupported it will be removed, as it should. Regretful you chose to see as a threat, but that's not my problem.

**Comment by markusressel** [comment]
Not sure about the maintenance state of this repo, but I am not sure it is necessary to remove it since it seems to work (reliably) for some people, but I am not familiar with the policies of HACS. If we would remove every software with unresolved issues we could trash all our electronic devices immediately though... since this doesnt seem do be security related I dont see the problem.

Can you link to the alternative integration?
Does it support old and new models alike? 
Maybe promoting the working integration is more constructive than "asking" for support on this one.

**Comment by user897943** [comment]
Why would I link it. I was super polite on my original post and thanked the developer first thing but you and the other lovely person are thumbing me down just because you're so sensitive? Thumb down this one too I'm sure it will help you feel better lol. Why would I help when you are all basically against me. When this thing finally breaks don't come crying. I'll go ahead and report and let the repo maintainers decide.

**Comment by SamJongenelen** [comment]
So, I stumbled upon this post to help: I think @user897943 is using a newer model of the AirPurifier series which runs COAP. 
That's this integration: https://github.com/betaboon/philips-airpurifier-coap 

I'd like to propose to add a warning/info to the readme of this repository.

**Comment by SamJongenelen** [comment]
I've got newer model working with this fork 
https://github.com/betaboon/philips-airpurifier-coap
