### ISSUE TITLE
AC3259/60 not working 

### ISSUE THREAD

**Issue by lowrisk75** [xMrVizzy/philips-airpurifier#27]
Configuration.yaml

```
fan:
  - platform: philips_airpurifier
    host: 192.168.5.109 ## same VLAN than HA

```

logs
```
2021-03-26 20:54:20 ERROR (MainThread) [homeassistant.components.fan] Error while setting up philips_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips-airpurifier/fan.py", line 109, in async_setup_platform
    client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/philips-airpurifier/fan.py", line 110, in <lambda>
    lambda: HTTPAirClient(config[CONF_HOST], False)
  File "/usr/local/lib/python3.8/site-packages/pyairctrl/http_client.py", line 108, in __init__
    self.load_key()
  File "/usr/local/lib/python3.8/site-packages/pyairctrl/http_client.py", line 156, in load_key
    self._get_key()
  File "/usr/local/lib/python3.8/site-packages/pyairctrl/http_client.py", line 119, in _get_key
    with urllib.request.urlopen(req) as response:
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by GeorgeSG** [comment]
It seems that your device is refusing an HTTP connection for some reason. My guess will be that it is a newer device that uses the CoAP protocol, not HTTP. If that's the case, this integration won't work for you, because it doesn't support CoAP.

A simple way to check is to open `http://192.168.5.109` in a browser and seeing what kind of response you get.

**Comment by SamJongenelen** [comment]
Yes. And try this repository as well: https://github.com/betaboon/philips-airpurifier-coap
