### ISSUE TITLE
Unable to load custom component

### ISSUE THREAD

**Issue by a-nicholls** [xMrVizzy/philips-airpurifier#3]
I've attempted to load the **Philips AirPurifier** custom component version 0.3.5  via the community on my hassbian venv install, edited configuration.xml 

```
fan:
  platform: philips_airpurifier
  host: 192.168.0.18
```

it results in the following error:

```
ERROR (MainThread) [homeassistant.config] Platform error: fan
Traceback (most recent call last):
  File "/srv/ha/lib/python3.7/site-packages/homeassistant/config.py", line 778, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/ha/lib/python3.7/site-packages/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ha/.homeassistant/custom_components/philips_airpurifier/fan.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

Should there be something in the manifest requirements or dependencies?

**Comment by xMrVizzy** [comment]
yes I will fix it
