### ISSUE TITLE
Speed mode Night

### ISSUE THREAD

**Issue by webosa** [xMrVizzy/philips-airpurifier#9]
Noticed this morning that my purifier reports speed as "Night", however on the speed selection list I don't have an option for "Night". I do see an option for "Sleep", but if I select that I am getting an "Failed to call service fan/turn_on. HTTP error 400: error.

All the other speed options work just fine.

**Comment by robroll** [comment]
Hi @webosa.
Night isn't in the set_speed list of options. What model air purifier have you got?

**Comment by webosa** [comment]
Hi, I got the AC1214/10, In the Philips app and Air Matters app it's called "Night Sensing Mode". Looks like if I have Auto Mode and it gets dark in the room the Night mode kicks in. The lights in the purifier dim/turn off. 

Currently I have the purifier set in Auto mode and the Philips app says: Auto Mode (Night Sensing Mode). Fan Speed: Auto. Below is what HA "more info" panel gives as speed attributes at the same time.
...
speed list: Auto Mode, Allergen Mode, Sleep Mode, Speed 1, Speed 2, Speed 3, Turbo
speed: Night
...

Looks like Night is listed as one of the modes in the code. 

if 'mode' in status:
            mode = status['mode']
            mode_str = {'P': 'Auto Mode', 'A': 'Allergen Mode', 'S': 'Sleep Mode', 'M': 'Manual', 'B': 'Bacteria', 'N': 'Night'}
            self._fan_speed = mode_str.get(mode, mode)


I don't mind that Night cannot be set manually, but Sleep perhaps should not be an option for this model as it doesn't seem to be supported by it.

**Comment by robroll** [comment]
Hi.
Night is listed in the code as an option to update (hence in the update section of the code) Home Assistant (as opposed control the purifier).

Look in the set_speed section for how Home Assistant can update the. You are right that Sleep Mode is listed in the set_speed section. This code doesn't detect model at the moment. It caters for all. You can remove easily remove Sleep Mode from SPEED_LIST (one item in the list) and set_speed (one elif) sections.

**Comment by webosa** [comment]
Ok, thanks

**Comment by zsawyer** [comment]
When I successfully connected my AC1214/10 it was in "Night Sensing Mode" using only this configuration:

```
# Philips AC1214/10
fan:
  platform: philips_airpurifier
  host: 192.168.0.45
```

This is what the log wrote:

```
2021-03-09 02:25:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration philips_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-09 02:25:56 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'philips_airpurifier'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_airpurifier'
2021-03-09 02:25:59 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform philips_airpurifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 603, in state_attributes
    data[ATTR_PERCENTAGE] = self.percentage
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 465, in percentage
    return self.speed_to_percentage(self.speed)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 549, in speed_to_percentage
    raise NotValidSpeedError(f"The speed {speed} is not a valid speed.")
homeassistant.components.fan.NotValidSpeedError: The speed Night is not a valid speed.
2021-03-09 02:26:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 603, in state_attributes
    data[ATTR_PERCENTAGE] = self.percentage
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 465, in percentage
    return self.speed_to_percentage(self.speed)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 549, in speed_to_percentage
    raise NotValidSpeedError(f"The speed {speed} is not a valid speed.")
homeassistant.components.fan.NotValidSpeedError: The speed Night is not a valid speed.
```

I'll try switching to https://github.com/kongo09/philips-airpurifier
